"""Metadata package for pytest-pgsnap."""

__title__ = "pytest-pgsnap"
__package_name__ = "pgsnap"
__description__ = "Just an experimental pytest plugin"
__version__ = "0.0.0"
__author__ = "Tony Narlock"
__github__ = "https://github.com/tony/pytest-pgsnap"
__docs__ = "https://pytest-pgsnap.git-pull.com"
__tracker__ = "https://github.com/tony/pytest-pgsnap/issues"
__pypi__ = "https://pypi.org/project/pytest-pgsnap/"
__email__ = "tony@git-pull.com"
__license__ = "MIT"
__copyright__ = "Copyright 2022- Tony Narlock"
